version: '3.8'

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env.production
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: securepassword
      MYSQL_DATABASE: crypto_production
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
